"""
Django settings for admin project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import sys

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-4else0!nmwp$$^z3(g#0u^xl1(5z01q0s)!fn_2*@^^c%qaf6b'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

PROJECT_ROOT = BASE_DIR.parent

sys.path.insert(0, str(PROJECT_ROOT))




# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'database',
    'krishi',
    'sfs',
    'skiltrix',
    'sonicora',
    'transport_hub',
    'user_profile',
    'shared_lib.sfs_core',
    'shared_lib',
    
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'admin.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'admin.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'as_main',
        'HOST': 'localhost',
        'PASSWORD': 'Ashokkumar21',
        'USER': 'root',
        'PORT': '3306',
    },
    'humbell': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'humbell',
        'HOST': 'localhost',
        'PASSWORD': 'Ashokkumar21',
        'USER': 'root',
        'PORT': '3306',
    },
    'krishi': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'krishi',
        'HOST': 'localhost',
        'PASSWORD': 'Ashokkumar21',
        'USER': 'root',
        'PORT': '3306',
    },
    'aaaab': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'aaaab',
        'HOST': 'localhost',
        'PASSWORD': 'Ashokkumar21',
        'USER': 'root',
        'PORT': '3306',
    },
    'aaaaa': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'aaaaa',
        'HOST': 'localhost',
        'PASSWORD': 'Ashokkumar21',
        'USER': 'root',
        'PORT': '3306',
    },
    
}

DATABASE_ROUTERS = [
    'shared_lib.db_router.AppDatabaseRouter'
]



# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR/"static"
]

APPEND_SLASH = False


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
